#!/usr/bin/env perl

use strict;
use warnings;

use JSON;
use Time::Local;
use DateTime;
use DateTime::Format::ISO8601;
use DateTime::Format::Duration;

# NOTE this should run as a cron

__PACKAGE__->new->run;

sub new {
    my $class = shift;
    bless {}, $class;
}

sub run {
    my $self = shift;

    $self->print_header;

    my $recent = $self->get_recent;
    foreach my $pull_request (@$recent) {
        $self->print_pull_request($pull_request);
    }

    $self->print_footer;
}

# read stats
sub get_stats {
    my $self = shift;
    open my $stats, '<', 'total_stats' or die $!;
    my $json = do { $/ = undef; <$stats> or die $! };
    my $list = from_json($json); # dies on bad data, maybe need nicer error?
    return $list;
}

# read recent activity dump from provided file
sub get_recent {
    my $self = shift;
    open my $recent, '<', 'recent' or die $!;
    my $json = do { $/ = undef; <$recent> or die $! };
    my $list = from_json($json); # dies on bad data, maybe need nicer error?
    return $self->filtered($list);
}

# TODO: read from a 'filter' file a list of usernames that we actually care about and only show those
sub filtered {
    my $self = shift;
    my $list = shift;
}

sub table {
    my $self = shift;
    my $stats = $self->get_stats->{'by_month'};

    my @months = qw(January Febrary March April May June July August September October November December);
    my $table = q{
        <tr>
            <th></th>
            <th colspan="3">Assignments</th>
            <th colspan="10">Pull Requests</th>
        </tr>
        <tr>
            <th>Month</th>
            <th>Total</th>
            <th>Done</th>
            <th>Percent</th>
            <th>Total</th>
            <th>Open</th>
            <th>Merged</th>
            <th>Closed</th>
         </tr>
        </tr>
    };
    foreach my $m (0..$#months) {
        next if ! $stats->[$m]->{'total'};
        $table .= join "\n", '<tr>', "<th>$months[$m]</th>", map { "<td>$_</td>" } map { $_ || '' } @{ $stats->[$m] }{ qw(total done percent pull_requests open merged closed) };
    }

    return $table;
}

sub print_header {
    my $self = shift;
    my $table = $self->table;

    print qq{
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="refresh" content="60">
        <style>
            /* from github.com */
            a { text-decoration: none }
            a:active, a:hover { outline: 0px none; text-decoration: none; }

            .issue-title-link { padding-right: 3px; margin-bottom: 2px; font-size: 15px; font-weight: bold; line-height: 1.2; color: #333 }
            .issue-title-link:hover { color: #4078C0; }
            .issue-nwo-link { color: #767676; }

            /* new stuff */
            .left  { float: left; }
            .right { float: right; }
            .cr    { clear: right; }

            .requestor { min-width: 10em; text-align: center; }
            .status .btn { min-width: 6em; font-weight: bold; }
            .summary { margin-left: 2em; }
            .special { background-color: yellow; }
            .glyphicon { top: 3px; }

            /* old stuff */
            /*  
            .time { color: #bbb; font-size: 75%; }
            .pull_request { border-top: 1px solid #dfdfdf; padding: 15px; }
            .summary { font-weight: bold }
            .title { color: #666; font-size: 85% }
            .merged { color: red; font-size: 40px; }
            */
        </style>
    </head>
    <body>

        <nav class="navbar navbar-default">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">YAPC::NA Pull Request Hackathon Dashboard</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <li><a href="http://yapcna.org">YAPC::NA</a></li>
                <li><a href="http://cpan-prc.org">CPAN PRC</a></li>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </nav>

        <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
            <div>
                <div class="panel panel-default panel-primary">
                    <div class="panel-heading">Info</div>
                    <div class="panel-body">
                        <h4>About</h4>
                        <p>Each month a CPAN distribution is assigned to you.
                        You have one month to submit at least one pull request.</p>

                        <h4>Sign up!</h4>
                        <p>Email your github username (and your PAUSE id if you have one) to neil at bowers dot com</p>

                        <h4>Community</h4>
                        <p><strong>IRC:</strong> Hang out with other PR challengers on <a href="http://irc.perl.org">irc.perl.org</a>#pr-challenge
                        (<a href="http://irclog.perlgeek.de/pr-challenge/today">Chat logs</a>)</p>
                        <p><strong>Mailing list:</strong> Subscribe via blank email to <a href="mailto:challenge-subscribe\@cpan-prc.org">challenge-subscribe\@cpan-prc.org</a></p>

                    </div>
                </div>
            </div>
            <div>
                <div class="panel panel-default panel-primary">
                    <div class="panel-heading">Stats</div>
                    <table class="table">$table</table>
                </div>
            </div>
            </div>
            <div class="col-md-8">
                <div class="panel panel-default panel-primary">
                    <div class="panel-heading">Recent Pull Requests</div>
                        <ul class="list-group">
    };
}

sub print_footer {
    print qq{
                    </ul>
                </div>
            </div>
            </div>
            <div class="row">
            </div>
        </div>
    </body>
</html>
    };
}

sub datetime {
    my $self = shift;
    my $date = shift;
    return if ! $date;
    return DateTime::Format::ISO8601->parse_datetime($date);
}
sub pretty_date {
    my $self = shift;
    my $dt = shift;
    return if ! $dt;
    return scalar localtime $dt->epoch;
}

sub pattern { shift->{'pattern'} ||= DateTime::Format::Duration->new(pattern => '%Y years, %m months, %e days, %k hours, %M minutes, %S seconds', normalize => 1) }
sub relative_date {
    my $self = shift;
    my $dt = shift;
    return if ! $dt;
    my $diff = DateTime->now->subtract_datetime($dt);
    my $short = $self->pattern->format_duration($diff);
    $short =~ s/\b0+\ \w+,//gxms;
    $short = join ', ', (split ', ', $short)[0..1];
    $short =~ s/\b(1\ \w+)s/$1/gxms; # 1 hours => 1 hour
    return $short . ' ago';
}

sub special {
    my $self = shift;

    return {} if ! -e 'special';
    return $self->{'special'} ||= do {
        open my $fh, '<', 'special' or warn $! and return {};
        my $lines = do { $/ = undef; <$fh> };
        my $special = { map { $_ => 1 } grep { $_ } split /\n/, lc $lines };
        $special;
    }
}

# TODO: highlight anything in the last 15 minutes in yellow!
sub print_pull_request {
    my $self = shift;
    my $pr = shift;

    my $created = $pr->{'created_at'};
    my $merged  = $pr->{'merged_at'} ? 'MERGED!' : '';
    my $closed  = $pr->{'closed_at'};
    my $dt = $self->datetime($created);
    my $pretty_created = $self->pretty_date($dt);
    my $relative = $self->relative_date($dt);
    my $requestor_url = $pr->{'user'}->{'html_url'};
    my $requestor_gravatar = $pr->{'user'}->{'avatar_url'} . '&s=60';
    my $requestor_username = $pr->{'user'}->{'login'};
    my $pull_request_url = $pr->{'_links'}->{'html'}->{'href'};
    my $pull_request_number = $pr->{'number'};
    my $author_url = $pr->{'base'}->{'repo'}->{'owner'}->{'html_url'};
    my $author_gravatar = $pr->{'base'}->{'repo'}->{'owner'}->{'avatar_url'} . '&s=60';
    my $author_username = $pr->{'base'}->{'repo'}->{'owner'}->{'login'};
    my $repo_url = $pr->{'base'}->{'repo'}->{'html_url'};
    my $repo_name = $pr->{'base'}->{'repo'}->{'name'};
    my $repo_description = $pr->{'base'}->{'repo'}->{'description'};
    my $pull_request_title = $pr->{'title'};
    my $is_special = $self->special->{lc $requestor_username} ? 'special' : '';
    my $num_comments = $pr->{'num_comments'};

    my $size = 45;
    use Data::Dumper qw(Dumper);
#    print "<pre>" . Dumper($pr) . "</pre>";

    # pull requester, pull receiver, repo, repo description?, pull request title?
    my $status_class = $merged ? 'success' : $closed ? 'danger' : 'info';
    my $status_text  = $merged ? 'Merged'  : $closed ? 'Closed' : 'Open';
    print qq{
        <li class="list-group-item $is_special clearfix">
            <div class="requestor left">
                <div><img alt="\$requestor_name" class="gravatar" height="$size" width="$size" src="$requestor_gravatar"></div>
                <div>$requestor_username</div>
            </div>
            <div class="status left"><a type="a" class="btn btn-$status_class">$status_text</a></div>
            <div class="summary left">
                <div>
                    <a class="issue-title-link issue-nwo-link" href="$repo_url">$author_username/$repo_name</a>
                    <a class="issue-title-link" href="$pull_request_url">$pull_request_title</a>
                </div>
                <div>
                    #$pull_request_number opened <time datetime="$created" title="$pretty_created">$relative</time>
                    by <a href="$requestor_url">$requestor_username</a>
                </div>
            </div>
            <div class="summary right cr">
                <a class="issue-title-link" href="$pull_request_url">
                    <span class="glyphicon glyphicon-comment"></span>
                    <span>&nbsp; $num_comments</span>
                </a>
            </div>
        </li>
    };
    return;
    print qq{
        <div class="pull_request $is_special">
            <div class="time"><time datetime="$created" title="$pretty_created">$relative</time></div>
            <div class="summary">
                <a href="$requestor_url"><img alt="\$requestor_name" class="gravatar" height="$size" width="$size" src="$requestor_gravatar">$requestor_username</a>
                <span>opened pull request</span>
                <a href="$pull_request_url">#$pull_request_number</a>
                <span>for</span>
                <br>
                <a href="$author_url"><img alt="\$author_name" class="gravatar" height="$size" width="$size" src="$author_gravatar">$author_username</a>
                <span>/</span>
                <a href="$repo_url">$repo_name</a>
                <span>($repo_description)</span>
            </div>
            <div class="title"><blockquote>$pull_request_title</blockquote></div>
            <div class="merged">$merged</div>
            <!-- div class="details">\$pull_request_details</div -->
        </div>
    };
}
