#!/usr/bin/env perl

use strict;
use warnings;

use JSON;

my @LINK_ORDER = qw(assigned module author repo);

my $rows = [];
foreach my $line (<>) {
    # yeah, yeah, regex parsing html is bad, I know, sue me
    my $row; @{ $row }{ @LINK_ORDER } = $line =~ /<a href='([^']*?)'/g;
    next if ! $row->{'assigned'};
    push $rows, $row;
}

print to_json $rows, { utf8 => 1, pretty => 1, canonical => 1 };

__END__

# <tr><td><a href='https://github.com/flimm'>flimm</a></td><td><a href='https://metacpan.org/release/Data-UUID'>Data-UUID</a></td><td><a href='https://metacpan.org/author/RJBS'>RJBS</a></td><td><a href='https://github.com/rjbs/Data-UUID'>rjbs/Data-UUID</a></td></tr>
